---
# tasks file for hello-world

- name: Debug Hello-World
  debug:
    msg: "Hello {{ hello_world_msg }}"

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Copy Template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644

- name: Create site root folder
  file:
    path: "{{ hello_world_root }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: Deploy index.html from template
  template:
    src: index.html.j2
    dest: "{{ hello_world_root }}/index.html"
    owner: www-data
    group: www-data
    mode: 0755

- name: Restart Nginx
  service:
    name: nginx
    state: restarted