---
# tasks file for hello-world

- name: Debug Hello-World
  debug:
    msg: "Hello {{ hello_world_msg }}"

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Copy Template
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/default
    owner: root
    group: root
    mode: 0644

- name: Create site root folder
  file:
    path: /opt/hello-world
    state: directory
    mode: 0755

#- name: Deploy index.html from template

#- name: Restart Nginx
